### ISSUE TITLE
n98-magerun.phar dev:template-var table prefix ignored

### ISSUE THREAD

**Issue by reesmcivor** [peterjaap/magerun-addons#13]
n98-magerun.phar dev:template-vars --addblocks=true doesn't look for table's that have been prefixed.

**Comment by peterjaap** [comment]
True. You should not use table prefixes.

**Comment by nickspiel** [comment]
That is a terrible reason to close this issue. Could we not fetch the prefix (if set) before running the script?

It is not really fair on people who may have inherited a database with prefixes or prefixed their tables when they were still learning the ropes.

I vote we reopen the issue.

**Comment by peterjaap** [comment]
I'm in favour of breaking things when they are bad practices instead of accommodating those that work with it, willingly or unwillingly. Sorry if this causes inconvenience for you right now.

**Comment by WouterSteen** [comment]
@peterjaap maybe you could make an n98-magerun extension that automatically removes table prefixes.

**Comment by peterjaap** [comment]
That would be totally sweet. And let it automatically run before running this command :trollface:

**Comment by riconeitzel** [comment]
I might be missing something important here, but why is using table prefixes bad practice? #askingForAFriend

**Comment by gwillem** [comment]
My friend would like to know too :D Googling for "magento table prefix BAD" only yields Trump tweets.

**Comment by peterjaap** [comment]
@riconeitzel @gwillem First of all, in the Magento ecosystem unfortunately we don't always run into high quality extensions. So you might run into an extension that hardcoded references a table without using the prefix. Although technically the extension builders' fault, the easy fix is to just never use table prefixes in the first place.

The second reason is that there is no reason at all to use the table prefixes. I can only imagine the reason why it was introduced was to seperate Magento tables from tables from other applications *that live in the same database*, which you should *never* do, because that means that application will also have access to the Magento tables. Imagine having to share one database with Magento and Wordpress.. yikes!

**Comment by riconeitzel** [comment]
@peterjaap From a security perspective I strongly have to disagree here: if you have standardized exploit scripts, that expect a magento admin user table to be named "admin_user" you're screwed if you *don't* use table prefixes.

I totally agree with you: Poorly written extensions can break functionalities if they're *not* using prefixes (as jisse (was it him?) mentioned … BUT I would NEVER install those extensions. And if a merchant is blind enough to do so without reviewing these AND is *ON TOP OF THAT* using the downloader … I'm sorry … so that's nothing I can help with.

But supporting table prefixes is not as bad as you say - m2ct …

So I'd like to kindly ask you to rethink your strategy - also for that open pull request :-) And I'd really like to invite your to a discussion about that.

I'm sure @gwillem is intrigued to discuss that in a small group ;-) (telegram!?)

**Comment by peterjaap** [comment]
If you got to the point where the hacker is able to open up a database just because he knows the table name, you've got 99 other problems.

**Comment by riconeitzel** [comment]
That's true … but shouldn't we do what ever is possible to make it harder for any aggressor?

**Comment by gwillem** [comment]
Ha @peterjaap! Kudo's for being principal. However, your reasoning seems contradictory:

> I'm in favour of breaking things when they are bad practices instead of accommodating those that work with it

vs

> Although technically the extension builders' fault, the easy fix is to just never use table prefixes in the first place.

FWIW, 99% of the Shoplift and other SQL related attacks I see on our platform are stopped with non-standard table names. Of course, you still gotta patch, but it's a pragmatic approach to limit the consequences of 0-day exploits.

**Comment by peterjaap** [comment]
But what percentage of those attacks would've been fought off when using a table prefix?

**Comment by springerin** [comment]
you're calling bad practice not supporting extensions, by using table prefix, that don't respect the use of table prefix. Seems to me a misuse of the words "bad practice". if it solves the issues with these extensions doesn't mean is a good practice. the fact that exists this "feature" can be debatable but since is there and someone might decide to use it if you want to be compliant to magento way don't see many choices.

**Comment by riconeitzel** [comment]
@springerin as this is free software and you're allowed to modify it yourself without complications … he doesn't have to support this feature. So I do understand @peterjaap if he says: It's not my incentive to support everyone's setup. I just like to share my piece of code; free to use.

**Comment by riconeitzel** [comment]
@peterjaap 

> But what percentage of those attacks would've been fought off when using a table prefix?

@gwillem already answered:

> 99% of the Shoplift and other SQL related attacks

**Comment by springerin** [comment]
@riconeitzel i am not arguing the fact that he has or not do this, totally agree is in his free choice. i argue the use of the words bad practice.

**Comment by infabo** [comment]
fun fact: partially supporting table-prefixes. good one. This is what is happening here. This is inconsistent and against the self-imposed best-practises called the "i don't give a fuck just because the Magento core supports it" for example.

**Comment by peterjaap** [comment]
True, will support table prefixes from now on. Just need to find the time to make it compatible (or do a PR and I'll merge, this time for reals).
